type: easyanimate
model_name: "easyanimate"
infer_name: "easyanimate-lora-generate"
train:
  model_path:
    # path to the pixart model or the hugging face model
    pretrained_model_name_or_path: "PixArt-alpha/PixArt-XL-2-512x512"
    # path to pretrained easyanimate checkpoint. Following are the links to available checkpoints.
    # https://dail-wlcb.oss-cn-wulanchabu.aliyuncs.com/dj-competition/modelscope_sora/models/easyanimate_mm_16x256x256_pretrain.safetensors
    # https://dail-wlcb.oss-cn-wulanchabu.aliyuncs.com/dj-competition/modelscope_sora/models/easyanimate_mm_16x512x512_pretrain.safetensors
    transformer_path: "/path/to/easyanimate_mm_16x256x256_pretrain.safetensors"
    lora_path: "../../outputs/demo-sandbox-data-partition/models/checkpoint-1.safetensors"

  infer_config:
    # must match the pretrained easyanimate checkpoint.
    image_size: 256
    prompt_info_path: "../../tools/mm_eval/vbench_metrics/VBench_mini_info.json"  # Use VBench_full_info.json for full eval.
    gpu_num: 1
    batch_size: 8
    mixed_precision: "bf16"
    video_num_per_prompt: 5
    seed: 43

  saving_config:
    output_video_dir: "../../outputs/demo-sandbox-data-partition/generate_videos"
